title: Blog Title
description: Blog Description
heading: This is heading text
subHeading: This is sub heading text
logo: /images/logo.svg
menu:
  - url: /
    label: Home
  - url: /sample-page
    label: Sample page
twitterUrl: https://twitter.com/?lang=en
facebookUrl: https://www.facebook.com/
instagramUrl: https://www.instagram.com/
dribbleUrl: https://dribbble.com/
githubUrl: https://github.com/
emailUrl: \#
rssUrl: \#
